spring.application.name=01-chat-openai

# server
spring.ai.openai.base-url=https://generativelanguage.googleapis.com
# endpoint on that server
# Together final url = https://generativelanguage.googleapis.com + /v1beta/openai/chat/completions
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions

spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.chat.options.model=models/gemini-3.6-flash
spring.ai.openai.chat.options.temperature=2