spring.ai.openai.base-url=https://openrouter.ai
spring.ai.openai.api-key=${passthekey}
spring.ai.openai.chat.completions-path=/api/v1/chat/completions
chat-model=openai/gpt-5
spring.ai.openai.chat.options.model=${chat-model}
spring.ai.openai.chat.options.max-tokens=1000